default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: events_for_users_dev
  username: etienne
  password: etienne
test:
  <<: *default
  database: events_for_users_test
  username: etienne
  password: etienne
production:
  <<: *default
  database: events_for_users
  username: sesame
  password: password
